/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/_vault'
import { Route as WelkomRouteImport } from './routes/welkom'
import { Route as VaultWorkspaceRouteImport } from './routes/_vault/_workspace'
import { Route as VaultInstellingenRouteImport } from './routes/_vault/instellingen'
import { Route as VaultWorkspaceIndexRouteImport } from './routes/_vault/_workspace/index'
import { Route as VaultWorkspaceKalenderRouteImport } from './routes/_vault/_workspace/kalender'

const VaultRoute = VaultRouteImport.update({
  id: '/_vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WelkomRoute = WelkomRouteImport.update({
  id: '/welkom',
  path: '/welkom',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultWorkspaceRoute = VaultWorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => VaultRoute,
} as any)
const VaultInstellingenRoute = VaultInstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => VaultRoute,
} as any)
const VaultWorkspaceIndexRoute = VaultWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultWorkspaceRoute,
} as any)
const VaultWorkspaceKalenderRoute = VaultWorkspaceKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => VaultWorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof VaultWorkspaceIndexRoute
  '/welkom': typeof WelkomRoute
  '/instellingen': typeof VaultInstellingenRoute
  '/kalender': typeof VaultWorkspaceKalenderRoute
}
export interface FileRoutesByTo {
  '/': typeof VaultWorkspaceIndexRoute
  '/welkom': typeof WelkomRoute
  '/instellingen': typeof VaultInstellingenRoute
  '/kalender': typeof VaultWorkspaceKalenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_vault': typeof VaultRouteWithChildren
  '/welkom': typeof WelkomRoute
  '/_vault/_workspace': typeof VaultWorkspaceRouteWithChildren
  '/_vault/instellingen': typeof VaultInstellingenRoute
  '/_vault/_workspace/kalender': typeof VaultWorkspaceKalenderRoute
  '/_vault/_workspace/': typeof VaultWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/welkom' | '/instellingen' | '/kalender'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/welkom' | '/instellingen' | '/kalender'
  id:
    | '__root__'
    | '/_vault'
    | '/welkom'
    | '/_vault/_workspace'
    | '/_vault/instellingen'
    | '/_vault/_workspace/kalender'
    | '/_vault/_workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VaultRoute: typeof VaultRouteWithChildren
  WelkomRoute: typeof WelkomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_vault': {
      id: '/_vault'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welkom': {
      id: '/welkom'
      path: '/welkom'
      fullPath: '/welkom'
      preLoaderRoute: typeof WelkomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vault/_workspace': {
      id: '/_vault/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VaultWorkspaceRouteImport
      parentRoute: typeof VaultRoute
    }
    '/_vault/instellingen': {
      id: '/_vault/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof VaultInstellingenRouteImport
      parentRoute: typeof VaultRoute
    }
    '/_vault/_workspace/': {
      id: '/_vault/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof VaultWorkspaceIndexRouteImport
      parentRoute: typeof VaultWorkspaceRoute
    }
    '/_vault/_workspace/kalender': {
      id: '/_vault/_workspace/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof VaultWorkspaceKalenderRouteImport
      parentRoute: typeof VaultWorkspaceRoute
    }
  }
}

interface VaultWorkspaceRouteChildren {
  VaultWorkspaceKalenderRoute: typeof VaultWorkspaceKalenderRoute
  VaultWorkspaceIndexRoute: typeof VaultWorkspaceIndexRoute
}

const VaultWorkspaceRouteChildren: VaultWorkspaceRouteChildren = {
  VaultWorkspaceKalenderRoute: VaultWorkspaceKalenderRoute,
  VaultWorkspaceIndexRoute: VaultWorkspaceIndexRoute,
}

const VaultWorkspaceRouteWithChildren = VaultWorkspaceRoute._addFileChildren(
  VaultWorkspaceRouteChildren,
)

interface VaultRouteChildren {
  VaultWorkspaceRoute: typeof VaultWorkspaceRouteWithChildren
  VaultInstellingenRoute: typeof VaultInstellingenRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultWorkspaceRoute: VaultWorkspaceRouteWithChildren,
  VaultInstellingenRoute: VaultInstellingenRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  VaultRoute: VaultRouteWithChildren,
  WelkomRoute: WelkomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
